services:
  app:
    image: cash-control:latest
    container_name: cashcontrol-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://cashcontrol-db:5432/cash_control
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - cashcontrol-network

  db:
    image: postgres:15
    container_name: cashcontrol-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: cash_control
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U app" ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    networks:
      - cashcontrol-network

networks:
  cashcontrol-network:
    driver: bridge