app:
  mock-data:
    users:
      - name: Thiago
        email: thiago@thiagoti.com
      - name: Gabriela
        email: gabrielamooraeess@gmail.com
        organization: thiago@thiagoti.com
    banks:
      - name: Millenium
        currency: EUR
    accounts:
      - name: Millenium
        bank: Millenium