spring:
  application:
    name: cash-control
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/cash_control
    driver-class-name: org.postgresql.Driver
    username: cashuser
    password: cashpass
  h2:
    console:
      enabled: false
  liquibase:
    parameters:
      jsonb.type: JSONB

app:
  user:
    name: Thiago Oliveira
    email: thiago@thiagoti.com
    password: ZuQvnq
  bank:
    name: Millenium
    currency: EUR
  account:
    name: Millenium

logging:
  level:
    ROOT: OFF
    dev.thiagooliveira: INFO
