app:
  mock-data:
    users:
      - name: Thiago
        email: thiago@thiagoti.com
      - name: Gabriela
        email: gabrielamooraeess@gmail.com
        organization: thiago@thiagoti.com
    categories:
      - name: Outros
        hashColor: "#148408"
        type: CREDIT
      - name: Outros
        hashColor: "#cb4b4b"
        type: DEBIT
    banks:
      - name: Millenium
        currency: EUR
    accounts:
      - name: Millenium
        bank: Millenium